### ISSUE TITLE
Available Tutorials

### ISSUE THREAD

**Issue by Astro-Sean** [thomasvrussell/sfft#1]
Hi Devs - is there any tutorials on how to use this pipeline?

(My apologises if I have overlooked this)

**Comment by thomasvrussell** [comment]
Hi,You may get it started using the scripts in test directory. I also plan to write a separate documentation for the software but have not yet found time to implement (sorry about that).Please let me know if you have any questions when you test the software!Thanks,LeiSent from my iPhoneOn Oct 6, 2023, at 09:32, Seán Brennan ***@***.***> wrote:﻿
Hi Devs - is there any tutorials on how to use this pipeline?
(My apologises if I have overlooked this)

**Comment by Astro-Sean** [comment]
Sorry - never replied to this

Found the tutorials and getting excellent results!
